name: 'check if workflows work'
description: 'test to check if workflows can be called from composite action'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: devops-testbed/intake/.github/workflows/reusable-workflow.yml@main
    - name: echo
      shell: bash  
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
              
