name: Add PR to project
on:
  workflow_call:
  workflow_dispatch: {}   
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get project data
        env:
          ORGANIZATION: "devops-testbed"
          PROJECT_NUMBER: 1
        run: echo $ORGANIZATION $PROJECT_NUMBER
        
      - name: Add PR to project
        env:
          PR_ID: ${{ github.event.pull_request.node_id }}
        run: echo $PR_ID

      - name: Get date
        run: echo "DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
        
      - name: use composite
        uses: devops-testbed/intake@main

      - name: use repo folder composite
        uses: devops-testbed/intake/folder-action@main
