name: devops-intake-main-reusable
on:
  workflow_call:
  workflow_dispatch: {}   
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
       
      - name: Get project data
        env:
          ORGANIZATION: "devops-testbed"
          PROJECT_NUMBER: 1
        run: echo $ORGANIZATION $PROJECT_NUMBER
        
      - name: Add PR to project
        env:
          PR_ID: ${{ github.event.pull_request.node_id }}
        run: echo $PR_ID

      - name: Get date
        run: echo "DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
        


      #- name: use repo folder composite devops-testbed/intake/folder-action@main
      #  uses: devops-testbed/intake/folder-action@main
