name: Org CI
on:
  workflow_call:
    inputs:
      projectid:
        description: 'Project'
        default: '1'
        required: false
        type: string
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
  build:
    runs-on: ubuntu-latest
    permissions:
      repository-projects: write 
    steps:
      - uses: actions/checkout@v3
