name: runselfhosted

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: ls
        run: ps -ef | grep -i Runner.Listener
      - name: cat /home/admin/actions-runner/.runner
        run: cat /home/admin/actions-runner/.runner
      - name: kill runner
        run: killall -9 Runner.Listener
